# Configurações básicas do site
title: Loyalty Card Documentation
description: Documentação completa do sistema Loyalty Card

# Informações de contato e links
github_username: seu-usuario
github_repo: loyalty-card
support_email: suporte@loyalty-card.com

# Configurações de navegação
show_downloads: false
google_analytics: # Seu ID do Google Analytics (opcional)

# Outras configurações
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Tema e plugins
remote_theme: pmarsceill/just-the-docs@v0.3.3
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-github-metadata

# Configurações do tema Just the Docs
search_enabled: true
heading_anchors: true
color_scheme: "dark"

# Links auxiliares
aux_links:
  "Loyalty Card no GitHub":
    - "//github.com/seu-usuario/loyalty-card"

# Estrutura de navegação
nav_order:
  home: 1
  architecture: 2
  diagrams: 3
  api: 4
  domain: 5
  operations: 6
  requirements: 7