# Configurações básicas do site
title: Loyalty Card Documentation
description: Documentação completa do sistema Loyalty Card

# Informações de contato e links
github_username: seu-usuario
github_repo: loyalty-card
support_email: suporte@loyalty-card.com

# Outras configurações
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag

# Tema
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc4

# Configurações do tema Just-the-Docs
search_enabled: true
heading_anchors: true
color_scheme: "dark"

# Links auxiliares
aux_links:
  "Loyalty Card no GitHub":
    - "//github.com/seu-usuario/loyalty-card"

# Navegação - alterado para formato compatível com Just-the-Docs
# Estrutura correta para o menu de navegação
nav_order:
  home: 1
  docs: 2

# Definição da estrutura de navegação
just_the_docs:
  collections:
    main:
      name: Documentação principal

# Organização da navegação (substitui 'nav')
navigation:
  - name: Home
    link: /
    nav_order: 1
    
  - name: Arquitetura
    link: /docs/architecture/
    nav_order: 2
    children:
      - name: AR-001 Onboarding
        link: /docs/architecture/ar-001-onboarding-de-clientes.html
        nav_order: 1
      - name: ADR-001 Decisões
        link: /docs/architecture/adr/adr-001-decisoes-arquiteturais-processo-onboarding.html
        nav_order: 2
        
  - name: Diagramas
    link: /docs/diagrams/
    nav_order: 3
    children:
      - name: Sequência de Onboarding
        link: /docs/diagrams/sequence-onboarding.html
        nav_order: 1
      - name: Estado de Onboarding
        link: /docs/diagrams/state-onboarding.html
        nav_order: 2
      - name: Arquitetura
        link: /docs/diagrams/architecture-overview.html
        nav_order: 3
        
  - name: API
    link: /docs/api/
    nav_order: 4
    
  - name: Domínio
    link: /docs/domain/
    nav_order: 5
    
  - name: Operações
    link: /docs/operations/
    nav_order: 6
    
  - name: Requisitos
    link: /docs/requirements/
    nav_order: 7

# Configurações de callouts
callouts:
  warning:
    title: Atenção
    color: red
  note:
    title: Nota
    color: blue
  tip:
    title: Dica
    color: green