# Configurações básicas do site
title: Loyalty Card Documentation
description: Documentação completa do sistema Loyalty Card

# Informações de contato e links
github_username: seu-usuario
github_repo: loyalty-card
support_email: suporte@loyalty-card.com

# Outras configurações
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag

# Tema
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc4

# Configurações do tema Just-the-Docs
search_enabled: true
heading_anchors: true
color_scheme: "dark"

# Links auxiliares
aux_links:
  "Loyalty Card no GitHub":
    - "//github.com/seu-usuario/loyalty-card"

# Configurações de navegação
nav:
  - title: Home
    url: /
  - title: Arquitetura
    url: /docs/architecture/
    children:
      - title: AR-001 Onboarding
        url: /docs/architecture/ar-001-onboarding-de-clientes
      - title: ADR-001 Decisões
        url: /docs/architecture/adr/adr-001-decisoes-arquiteturais-processo-onboarding
  - title: Diagramas
    url: /docs/diagrams/
    children:
      - title: Sequência de Onboarding
        url: /docs/diagrams/sequence-onboarding
      - title: Estado de Onboarding
        url: /docs/diagrams/state-onboarding
      - title: Arquitetura
        url: /docs/diagrams/architecture-overview
  - title: API
    url: /docs/api/
  - title: Domínio
    url: /docs/domain/
  - title: Operações
    url: /docs/operations/
  - title: Requisitos
    url: /docs/requirements/

# Configurações de callouts
callouts:
  warning:
    title: Atenção
    color: red
  note:
    title: Nota
    color: blue
  tip:
    title: Dica
    color: green