# Configurações básicas do site
title: Loyalty Card Documentation
description: Documentação completa do sistema Loyalty Card
theme: jekyll-theme-cayman

# Informações de contato e links
github_username: seu-usuario
github_repo: loyalty-card
support_email: suporte@loyalty-card.com

# Configurações de navegação
show_downloads: false
google_analytics: # Seu ID do Google Analytics (opcional)

# Outras configurações
markdown: kramdown

# Habilitar processamento de mermaid
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: mathjax

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag

# Navegação personalizada (transformada em sidebar)
sidebar:
  - title: Home
    url: /
  - title: Arquitetura
    url: /architecture
    children:
      - title: Visão Geral
        url: /architecture/overview
      - title: ADRs
        url: /architecture/adrs
  - title: APIs
    url: /api-flows
  - title: Guia do Usuário
    url: /user-guide
  - title: RFCs
    url: /rfcs