# Configurações básicas do site
title: Loyalty Card Documentation
description: Documentação completa do sistema Loyalty Card
theme: jekyll-theme-cayman

# Informações de contato e links
github_username: seu-usuario
github_repo: loyalty-card
support_email: suporte@loyalty-card.com

# Configurações de navegação
show_downloads: false
google_analytics: # Seu ID do Google Analytics (opcional)

# Outras configurações
markdown: kramdown

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag

# Navegação personalizada
navbar:
  - title: Home
    url: /
  - title: Arquitetura
    url: /architecture
  - title: APIs
    url: /api-flows